# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 043cdac7514c5203ce2269e7280edcdf44dfef1d9f0f670efd3fb79618a17649b07fa68c30f78bb87296a941d0add4b563079b050cda8d3dd0c4585e8c171477

test:
  secret_key_base: f19069e7a58839d8bef3c9ad0a7e293167f6dfbf5b223f6fe04c25ec111740887f64a857965cbe495baa03ddfae03caeea92b3f071a917790c56743a44c87a23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
